services:
  todo-app:
    build: ./
    command: ["./wait-for-it.sh", "todo-db:5432", "--", "./todo-app"]
    image: todo-app
    container_name: todo-app
    environment:
      - DB_PASSWORD=secret
    ports:
      - "8080:8080"
    depends_on:
      - todo-db
    networks:
      - todo-network

  todo-db:
    restart: always
    image: postgres:latest
    container_name: todo-db
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network:
